# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calci.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, SimpleCalculator):
        SimpleCalculator.setObjectName("MainWindow")
        SimpleCalculator.resize(281, 483)
        self.centralwidget = QtWidgets.QWidget(SimpleCalculator)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonC = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonC.setGeometry(QtCore.QRect(0, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonC.setFont(font)
        self.pushButtonC.setAutoFillBackground(False)
        self.pushButtonC.setObjectName("pushButtonC")
        self.pushButtonPercent = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPercent.setGeometry(QtCore.QRect(70, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonPercent.setFont(font)
        self.pushButtonPercent.setAutoFillBackground(False)
        self.pushButtonPercent.setObjectName("pushButtonPercent")
        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(0, 220, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton4.setFont(font)
        self.pushButton4.setAutoFillBackground(False)
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton7.setGeometry(QtCore.QRect(0, 150, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton7.setFont(font)
        self.pushButton7.setAutoFillBackground(False)
        self.pushButton7.setObjectName("pushButton7")
        self.pushButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(140, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setAutoFillBackground(False)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(0, 290, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton1.setFont(font)
        self.pushButton1.setAutoFillBackground(False)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton0.setGeometry(QtCore.QRect(0, 360, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton0.setFont(font)
        self.pushButton0.setAutoFillBackground(False)
        self.pushButton0.setObjectName("pushButton0")
        self.pushButton00 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton00.setGeometry(QtCore.QRect(70, 360, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton00.setFont(font)
        self.pushButton00.setAutoFillBackground(False)
        self.pushButton00.setObjectName("pushButton00")
        self.pushButton8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton8.setGeometry(QtCore.QRect(70, 150, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton8.setFont(font)
        self.pushButton8.setAutoFillBackground(False)
        self.pushButton8.setObjectName("pushButton8")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(70, 290, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton2.setFont(font)
        self.pushButton2.setAutoFillBackground(False)
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton5.setGeometry(QtCore.QRect(70, 220, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton5.setFont(font)
        self.pushButton5.setAutoFillBackground(False)
        self.pushButton5.setObjectName("pushButton5")
        self.pushButtonDeci = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDeci.setGeometry(QtCore.QRect(140, 360, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonDeci.setFont(font)
        self.pushButtonDeci.setAutoFillBackground(False)
        self.pushButtonDeci.setObjectName("pushButtonDeci")
        self.pushButton9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton9.setGeometry(QtCore.QRect(140, 150, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton9.setFont(font)
        self.pushButton9.setAutoFillBackground(False)
        self.pushButton9.setObjectName("pushButton9")
        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(140, 290, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton3.setFont(font)
        self.pushButton3.setAutoFillBackground(False)
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton6.setGeometry(QtCore.QRect(140, 220, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton6.setFont(font)
        self.pushButton6.setAutoFillBackground(False)
        self.pushButton6.setStyleSheet("rgb")
        self.pushButton6.setObjectName("pushButton6")
        self.toolButton_Divide = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_Divide.setGeometry(QtCore.QRect(210, 80, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.toolButton_Divide.setFont(font)
        self.toolButton_Divide.setAutoFillBackground(False)
        self.toolButton_Divide.setObjectName("toolButton_Divide")
        self.toolButton_Multi = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_Multi.setGeometry(QtCore.QRect(210, 150, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.toolButton_Multi.setFont(font)
        self.toolButton_Multi.setAutoFillBackground(False)
        self.toolButton_Multi.setObjectName("toolButton_Multi")
        self.toolButton_Plus = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_Plus.setGeometry(QtCore.QRect(210, 290, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.toolButton_Plus.setFont(font)
        self.toolButton_Plus.setAutoFillBackground(False)
        self.toolButton_Plus.setObjectName("toolButton_Plus")
        self.toolButton_Minus = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_Minus.setGeometry(QtCore.QRect(210, 220, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.toolButton_Minus.setFont(font)
        self.toolButton_Minus.setAutoFillBackground(False)
        self.toolButton_Minus.setObjectName("toolButton_Minus")
        self.toolButton_Equal = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_Equal.setGeometry(QtCore.QRect(210, 360, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.toolButton_Equal.setFont(font)
        self.toolButton_Equal.setAutoFillBackground(False)
        self.toolButton_Equal.setObjectName("toolButton_Equal")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 281, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalLayoutWidget.sizePolicy().hasHeightForWidth())
        self.verticalLayoutWidget.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        SimpleCalculator.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SimpleCalculator)
        self.statusbar.setObjectName("statusbar")
        SimpleCalculator.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(SimpleCalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 281, 26))
        self.menubar.setObjectName("menubar")
        self.menuBasic = QtWidgets.QMenu(self.menubar)
        self.menuBasic.setObjectName("menuBasic")
        SimpleCalculator.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuBasic.menuAction())

        self.retranslateUi(SimpleCalculator)
        QtCore.QMetaObject.connectSlotsByName(SimpleCalculator)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonC.setText(_translate("MainWindow", "C"))
        self.pushButtonPercent.setText(_translate("MainWindow", "%"))
        self.pushButton4.setText(_translate("MainWindow", "4"))
        self.pushButton7.setText(_translate("MainWindow", "7"))
        self.pushButtonBack.setText(_translate("MainWindow", "←"))
        self.pushButton1.setText(_translate("MainWindow", "1"))
        self.pushButton0.setText(_translate("MainWindow", "0"))
        self.pushButton00.setText(_translate("MainWindow", "00"))
        self.pushButton8.setText(_translate("MainWindow", "8"))
        self.pushButton2.setText(_translate("MainWindow", "2"))
        self.pushButton5.setText(_translate("MainWindow", "5"))
        self.pushButtonDeci.setText(_translate("MainWindow", "."))
        self.pushButton9.setText(_translate("MainWindow", "9"))
        self.pushButton3.setText(_translate("MainWindow", "3"))
        self.pushButton6.setText(_translate("MainWindow", "6"))
        self.toolButton_Divide.setText(_translate("MainWindow", "/"))
        self.toolButton_Multi.setText(_translate("MainWindow", "x"))
        self.toolButton_Plus.setText(_translate("MainWindow", "+"))
        self.toolButton_Minus.setText(_translate("MainWindow", "-"))
        self.toolButton_Equal.setText(_translate("MainWindow", "="))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.menuBasic.setTitle(_translate("MainWindow", "Basic"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
